// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size
// @generated from protobuf file "pwt.proto" (package "pwt", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message pwt.Token
 */
export interface Token {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp valid_until = 1
     */
    validUntil?: Timestamp;
    /**
     * @generated from protobuf field: bytes claims = 2
     */
    claims: Uint8Array;
}
/**
 * @generated from protobuf message pwt.SignedToken
 */
export interface SignedToken {
    /**
     * @generated from protobuf field: bytes data = 1
     */
    data: Uint8Array;
    /**
     * @generated from protobuf field: bytes signature = 2
     */
    signature: Uint8Array;
}
// @generated message type with reflection information, may provide speed optimized methods
class Token$Type extends MessageType<Token> {
    constructor() {
        super("pwt.Token", [
            { no: 1, name: "valid_until", kind: "message", T: () => Timestamp },
            { no: 2, name: "claims", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pwt.Token
 */
export const Token = new Token$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SignedToken$Type extends MessageType<SignedToken> {
    constructor() {
        super("pwt.SignedToken", [
            { no: 1, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pwt.SignedToken
 */
export const SignedToken = new SignedToken$Type();
