{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Pwt.Internals_ exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 3.19.0
- the following specification files: `pwt.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


-}

import Bytes
import Maybe
import Proto.Google.Protobuf.Internals_
import Protobuf.Decode
import Protobuf.Encode
import Protobuf.Types.Int64


{-| The field numbers for the fields of `Proto__Pwt__Complex`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Pwt__Complex : { validUntil : Int, userId : Int, userName : Int, email : Int, roles : Int }
fieldNumbersProto__Pwt__Complex =
    { validUntil = 1, userId = 2, userName = 3, email = 4, roles = 5 }


{-| Default for Proto__Pwt__Complex. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Pwt__Complex : Proto__Pwt__Complex
defaultProto__Pwt__Complex =
    { validUntil = Nothing, userId = Protobuf.Types.Int64.fromInts 0 0, userName = "", email = "", roles = [] }


{-| Declares how to decode a `Proto__Pwt__Complex` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Pwt__Complex : Protobuf.Decode.Decoder Proto__Pwt__Complex
decodeProto__Pwt__Complex =
    Protobuf.Decode.message
        defaultProto__Pwt__Complex
        [ Protobuf.Decode.optional
            1
            (Protobuf.Decode.map Just Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Timestamp)
            (\a r -> { r | validUntil = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.int64 (\a r -> { r | userId = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | userName = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.string (\a r -> { r | email = a })
        , Protobuf.Decode.repeated 5 decodeProto__Pwt__Role .roles (\a r -> { r | roles = a })
        ]


{-| Declares how to encode a `Proto__Pwt__Complex` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Pwt__Complex : Proto__Pwt__Complex -> Protobuf.Encode.Encoder
encodeProto__Pwt__Complex value =
    Protobuf.Encode.message
        [ ( 1
          , (Maybe.map Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Timestamp
                >> Maybe.withDefault Protobuf.Encode.none
            )
                value.validUntil
          )
        , ( 2, Protobuf.Encode.int64 value.userId )
        , ( 3, Protobuf.Encode.string value.userName )
        , ( 4, Protobuf.Encode.string value.email )
        , ( 5, Protobuf.Encode.list encodeProto__Pwt__Role value.roles )
        ]


{-| `Proto__Pwt__Complex` message


-}
type alias Proto__Pwt__Complex =
    { validUntil : Maybe Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Timestamp
    , userId : Protobuf.Types.Int64.Int64
    , userName : String
    , email : String
    , roles : List Proto__Pwt__Role
    }


{-| The field numbers for the fields of `Proto__Pwt__Simple`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Pwt__Simple : { someClaim : Int }
fieldNumbersProto__Pwt__Simple =
    { someClaim = 2 }


{-| Default for Proto__Pwt__Simple. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Pwt__Simple : Proto__Pwt__Simple
defaultProto__Pwt__Simple =
    { someClaim = "" }


{-| Declares how to decode a `Proto__Pwt__Simple` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Pwt__Simple : Protobuf.Decode.Decoder Proto__Pwt__Simple
decodeProto__Pwt__Simple =
    Protobuf.Decode.message
        defaultProto__Pwt__Simple
        [ Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | someClaim = a }) ]


{-| Declares how to encode a `Proto__Pwt__Simple` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Pwt__Simple : Proto__Pwt__Simple -> Protobuf.Encode.Encoder
encodeProto__Pwt__Simple value =
    Protobuf.Encode.message [ ( 2, Protobuf.Encode.string value.someClaim ) ]


{-| `Proto__Pwt__Simple` message


-}
type alias Proto__Pwt__Simple =
    { someClaim : String }


{-| The field numbers for the fields of `Proto__Pwt__Token`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Pwt__Token : { validUntil : Int, claims : Int }
fieldNumbersProto__Pwt__Token =
    { validUntil = 1, claims = 2 }


{-| Default for Proto__Pwt__Token. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Pwt__Token : Proto__Pwt__Token
defaultProto__Pwt__Token =
    { validUntil = Nothing, claims = Protobuf.Encode.encode <| Protobuf.Encode.string "" }


{-| Declares how to decode a `Proto__Pwt__Token` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Pwt__Token : Protobuf.Decode.Decoder Proto__Pwt__Token
decodeProto__Pwt__Token =
    Protobuf.Decode.message
        defaultProto__Pwt__Token
        [ Protobuf.Decode.optional
            1
            (Protobuf.Decode.map Just Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Timestamp)
            (\a r -> { r | validUntil = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.bytes (\a r -> { r | claims = a })
        ]


{-| Declares how to encode a `Proto__Pwt__Token` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Pwt__Token : Proto__Pwt__Token -> Protobuf.Encode.Encoder
encodeProto__Pwt__Token value =
    Protobuf.Encode.message
        [ ( 1
          , (Maybe.map Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Timestamp
                >> Maybe.withDefault Protobuf.Encode.none
            )
                value.validUntil
          )
        , ( 2, Protobuf.Encode.bytes value.claims )
        ]


{-| `Proto__Pwt__Token` message


-}
type alias Proto__Pwt__Token =
    { validUntil : Maybe Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Timestamp, claims : Bytes.Bytes }


{-| Default for Proto__Pwt__Role. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Pwt__Role : Proto__Pwt__Role
defaultProto__Pwt__Role =
    Proto__Pwt__ReadFeatureFoo


{-| Declares how to encode a `Proto__Pwt__Role` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Pwt__Role : Proto__Pwt__Role -> Protobuf.Encode.Encoder
encodeProto__Pwt__Role value =
    Protobuf.Encode.int32 <|
        case value of
            Proto__Pwt__ReadFeatureFoo ->
                0

            Proto__Pwt__WriteFeatureFoo ->
                1

            Proto__Pwt__ReadFeatureBar ->
                2

            Proto__Pwt__WriteFeatureBar ->
                3

            Proto__Pwt__RoleUnrecognized_ i ->
                i


{-| Declares how to decode a `Proto__Pwt__Role` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Pwt__Role : Protobuf.Decode.Decoder Proto__Pwt__Role
decodeProto__Pwt__Role =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        Proto__Pwt__ReadFeatureFoo

                    1 ->
                        Proto__Pwt__WriteFeatureFoo

                    2 ->
                        Proto__Pwt__ReadFeatureBar

                    3 ->
                        Proto__Pwt__WriteFeatureBar

                    _ ->
                        Proto__Pwt__RoleUnrecognized_ i
            )


{-| `Proto__Pwt__Role` enumeration


-}
type Proto__Pwt__Role
    = Proto__Pwt__ReadFeatureFoo
    | Proto__Pwt__WriteFeatureFoo
    | Proto__Pwt__ReadFeatureBar
    | Proto__Pwt__WriteFeatureBar
    | Proto__Pwt__RoleUnrecognized_ Int
